/** Browser checks for the shipped control panel. Local fixture transport; no external model calls. */
import assert from 'node:assert/strict'
import {createServer} from 'node:http'
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs'
import {resolve,join} from 'node:path'
import {pathToFileURL} from 'node:url'
const {chromium}=await import(pathToFileURL(process.env.DPSWARM_TEST_PLAYWRIGHT).href)
const out=resolve('.tmp/panel-redesign-20260907');mkdirSync(out,{recursive:true})
let state={spec:{revision:2,max_open_work_items:4,max_active_node_points:8,subteam_point_ratio:.5,max_depth:2,max_team_workers:3,max_attempts:3,deadline_seconds:14400,node_wallclock_timeout:7200,root_acceptance_mode:'lead'},snapshot:{graph_revision:0,open_worker_slots_used:1,active_points:3,seal_phase:{root:'open'},work_items:{'wi-root01':{kind:'root',depth:1,acceptance:null,attempt:1,team:'root'},'wi-implementation':{kind:'derive',depth:2,acceptance:'accepted',attempt:1,team:'root'},'wi-verification':{kind:'derive',depth:2,acceptance:'submitted',attempt:1,team:'root'}},nodes:{'node-lead01':{role:'root-lead',lifecycle:'active',blocked:'none',epoch:0},'node-worker01':{role:'worker',lifecycle:'active',blocked:'none',epoch:0},'node-worker02':{role:'worker',lifecycle:'completed',blocked:'none',epoch:0}}}}
let failStatus=false,failSave=false,requests=[],bridge=false,notStarted=false
let events=[{seq:1,kind:'work_item_submitted',ts:1788757200,payload:{item_id:'wi-verification',content:'<img src=x onerror="window.XSS=true">'}},{seq:2,kind:'work_item_accepted',ts:1788757240,payload:{item_id:'wi-implementation',evidence_ready:true}},{seq:3,kind:'node_drained',ts:1788757260,payload:{node_id:'node-worker02'}}]
const observation={token_totals:{input:34000,output:1400,cost:null},token_unknown_counts:{input:0,output:0,cost:1},events:3}
const html=readFileSync('dpswarm-plugin/dpswarm/static/index.html','utf8').replace('{{DPSWARM_TOKEN}}','fixture-capability')
const server=createServer(async(req,res)=>{let body='';for await(const c of req)body+=c;requests.push({url:req.url,method:req.method,session:req.headers['x-dpswarm-session'],body:body?JSON.parse(body):null});if(req.url.startsWith('/api/')){res.setHeader('Content-Type','application/json');if(req.url.startsWith('/api/status')){if(failStatus){res.writeHead(503);res.end(JSON.stringify({error:'fixture offline'}));return}res.end(JSON.stringify(notStarted?{state:'not_started',snapshot:null,bridge:{session_isolation:true}}:{...state,...(bridge?{bridge:{session_isolation:true}}:{})}));return}if(req.url.startsWith('/api/events')){res.end(JSON.stringify({events,total:events.length}));return}if(req.url==='/api/observation'){res.end(JSON.stringify(observation));return}if(req.url==='/api/spec'){if(failSave){res.writeHead(400);res.end(JSON.stringify({error:'fixture save rejected'}));return}state.spec={...state.spec,...JSON.parse(body),revision:state.spec.revision+1};res.end(JSON.stringify({ok:true,revision:state.spec.revision}));return}res.end(JSON.stringify({ok:true,result:{actions:['demo']}}));return}res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html)})
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050},colorScheme:'light'}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000)
try{
 await page.goto(base);await page.getByText('已连接',{exact:true}).waitFor();assert.equal(await page.locator('#stats .stat').count(),4);assert.equal(await page.locator('#items tr').count(),3);assert.equal(await page.locator('#costUsd').innerText(),'未知');assert.equal(await page.locator('#inputTokens').innerText(),'34,000');checks.push('real_schema_metrics_and_unknown_cost')
 assert.equal(requests.filter(r=>r.method==='POST').length,0);checks.push('load_is_read_only')
 await page.screenshot({path:join(out,'dashboard-light.png'),fullPage:true})
 await page.getByRole('tab',{name:'成员'}).click();assert.equal(await page.locator('#nodes tr').count(),3);await page.getByRole('tab',{name:'成员'}).press('ArrowRight');assert.equal(await page.locator('#panel-teams').isVisible(),true);assert.equal(await page.locator('#teams tr').count(),1);await page.getByRole('tab',{name:'任务'}).click();checks.push('accessible_tabs_and_team_data')
 await page.locator('#eventFilter').selectOption('delivery');assert.equal(await page.locator('.event').count(),2);await page.locator('.event').last().locator('summary').click();await page.getByRole('button',{name:'刷新状态',exact:true}).click();await page.waitForTimeout(250);assert.equal(await page.locator('.event[open]').count(),1);assert.equal(await page.locator('.event img').count(),0);assert.equal(await page.evaluate(()=>window.XSS),undefined);checks.push('activity_filter_full_payload_xss_safe_and_expansion_kept')
 await page.locator('#eventFilter').selectOption('problem');await page.getByText('暂无异常',{exact:true}).waitFor();await page.locator('#eventFilter').selectOption('all')
 await page.getByText('运行边界',{exact:true}).click();await page.getByLabel('同时运行的成员',{exact:true}).fill('6');await page.waitForTimeout(3400);assert.equal(await page.getByLabel('同时运行的成员',{exact:true}).inputValue(),'6');checks.push('polling_preserves_edit_draft')
 failSave=true;await page.getByRole('button',{name:'保存边界',exact:true}).click();await page.locator('#toast').filter({hasText:'fixture save rejected'}).waitFor();assert.equal(await page.getByLabel('同时运行的成员',{exact:true}).inputValue(),'6');failSave=false;await page.getByRole('button',{name:'保存边界',exact:true}).click();await page.waitForFunction(()=>document.getElementById('rev').textContent==='v3');assert.equal(state.spec.max_open_work_items,6);checks.push('save_rejection_retains_draft_and_success_applies')
 await page.getByText('维护操作',{exact:true}).click();await page.getByRole('button',{name:'检查调度',exact:true}).click();await page.waitForTimeout(150);assert.equal(requests.filter(r=>r.url==='/api/tick').at(-1).method,'POST');checks.push('scheduler_uses_post')
 const before=requests.filter(r=>r.url==='/api/directive').length;await page.getByRole('button',{name:'停止任务',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();assert.equal(requests.filter(r=>r.url==='/api/directive').length,before);await page.getByRole('button',{name:'停止任务',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'停止任务',exact:true}).click();await page.waitForTimeout(200);assert.equal(requests.filter(r=>r.url==='/api/directive').at(-1).body.kind,'terminal');checks.push('stop_requires_explicit_dialog_action')
 failStatus=true;await page.getByRole('button',{name:'刷新状态',exact:true}).click();await page.getByRole('alert').filter({hasText:'fixture offline'}).waitFor();assert.equal(await page.locator('#items tr').count(),3);assert.equal(await page.getByRole('button',{name:'停止任务',exact:true}).isDisabled(),true);failStatus=false;await page.getByRole('button',{name:'刷新状态',exact:true}).click();await page.getByText('已连接',{exact:true}).waitFor();checks.push('offline_keeps_data_and_disables_writes')
 await page.getByRole('button',{name:'查看设置入口 ↗'}).click();await page.getByRole('dialog',{name:'在 DPH 中调整模型'}).waitFor();await page.getByRole('button',{name:'知道了',exact:true}).click();checks.push('settings_location_in_native_host')
 await page.getByRole('button',{name:'切换明暗主题'}).click();await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.getByText('已连接',{exact:true}).waitFor();await page.screenshot({path:join(out,'dashboard-dark.png'),fullPage:true});checks.push('theme_persists')
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(out,'dashboard-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.evaluate(()=>[...document.querySelectorAll('.side-stack > .card')].every(c=>Math.abs(c.getBoundingClientRect().width-document.querySelector('.side-stack').getBoundingClientRect().width)<2)),true);checks.push('mobile_no_page_overflow','mobile_sidebar_cards_fill_width')
 bridge=true;notStarted=true;await page.goto(base+'/?session=fresh-session#dph='+encodeURIComponent('http://127.0.0.1:3080'));await page.getByText(/当前任务尚未启动协作/).waitFor();assert.equal(await page.locator('#demoPanel').isVisible(),false);assert.equal(await page.getByRole('button',{name:'停止任务',exact:true}).isDisabled(),true);assert.equal(await page.locator('#hostSettingsLink').getAttribute('href'),'http://127.0.0.1:3080/?dpswarm-settings=1');assert.equal(requests.filter(r=>r.url==='/api/status').at(-1).session,'fresh-session');checks.push('unstarted_session_empty_state_and_scoping','loopback_host_settings_link')
 await page.goto(base+'/#dph='+encodeURIComponent('https://evil.example'));await page.getByText('已连接',{exact:true}).waitFor();assert.equal(await page.locator('#hostSettingsLink').isVisible(),false);checks.push('external_host_link_rejected')
 notStarted=false;await page.goto(base);await page.getByText(/当前为服务概览/).waitFor();assert.equal(await page.getByRole('button',{name:'停止任务',exact:true}).isDisabled(),true);checks.push('unscoped_bridge_view_is_read_only')
 assert.deepEqual(errors,[]);checks.push('no_browser_errors');writeFileSync(join(out,'browser-results.json'),JSON.stringify({passed:true,checks,external_model_calls:0},null,2));console.log(JSON.stringify({passed:checks.length,checks}))
}finally{await browser.close();await new Promise(r=>server.close(r))}
